FROM gcr.io/distroless/base-debian12:nonroot
LABEL org.opencontainers.image.source="https://github.com/stigenai/autosql"
ARG TARGETARCH
COPY image/${TARGETARCH}/autosql /autosql
USER nonroot:nonroot
ENTRYPOINT ["/autosql"]
