package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	"autosql/pkg/plugin"
	"autosql/pkg/schema"
)

func renderResource(kind schema.Kind, name schema.Name, spec string, deps ...schema.Dependency) schema.Resource {
	r := schema.Resource{Kind: kind, Name: name, Spec: json.RawMessage(spec), Dependencies: deps}
	r.ID = schema.StableID(kind, name)
	return r
}
func projection(parent schema.Resource, name, typ string) schema.Resource {
	return renderResource(schema.KindColumn, schema.Name{Schema: parent.Name.Schema, Name: name, Parent: parent.ID}, `{"not_null":false,"ordinal":1,"type":"`+typ+`"}`, schema.Dependency{Target: parent.ID, Type: schema.DependencyContains})
}

func TestRenderNoopAllowsRichInspectedMetadataButChangesFailClosed(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	ns.Annotations = map[string]string{"comment": "inspected schema"}
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, `{"identity":"future","not_null":true,"ordinal":1,"type":"bigint"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	rich := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, column}}, Annotations: map[string]string{"dialect": "postgresql"}}
	rich.Normalize()

	changes := schema.ChangeSet{Version: schema.ChangeVersion}
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: rich, Desired: rich})
	if err != nil || len(out) != 0 {
		t.Fatalf("no-op rich inspection out=%+v err=%v", out, err)
	}

	empty := schema.Document{Version: schema.SchemaVersion, Annotations: map[string]string{"dialect": "postgresql"}}
	changes, err = schema.Diff(empty, rich, schema.DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	out, err = New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: empty, Desired: rich})
	if err == nil || len(out) != 0 {
		t.Fatalf("metadata-bearing mutation did not fail closed: out=%+v err=%v", out, err)
	}
}

func TestIdentityColumnCreationAndValidation(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	always := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "always_id", Parent: table.ID}, `{"identity":"always","not_null":true,"ordinal":1,"type":"bigint"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	byDefault := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "default_id", Parent: table.ID}, `{"identity":"by_default","not_null":true,"ordinal":2,"type":"bigint"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	doc, err := New().Normalize(context.Background(), schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, always, byDefault}}})
	if err != nil {
		t.Fatal(err)
	}
	out, err := RenderDocument(context.Background(), doc, nil)
	if err != nil {
		t.Fatal(err)
	}
	joined := ""
	for _, statement := range out {
		joined += statement.SQL + "\n"
	}
	for _, clause := range []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"} {
		if !strings.Contains(joined, clause) {
			t.Errorf("missing %q in:\n%s", clause, joined)
		}
	}
	for _, resource := range doc.Graph.Resources {
		if resource.Kind != schema.KindColumn {
			continue
		}
		identity := stringValue(spec(resource), "identity")
		if identity != "a" && identity != "d" {
			t.Errorf("identity was not canonicalized: %s=%q", resource.Name.Name, identity)
		}
	}

	for name, values := range map[string]map[string]any{
		"invalid":               {"identity": "sometimes"},
		"default combination":   {"identity": "a", "default": "1"},
		"generated combination": {"identity": "d", "generated": "s", "default": "id + 1"},
	} {
		t.Run(name, func(t *testing.T) {
			specification := map[string]any{"type": "bigint", "not_null": true, "ordinal": 1}
			for key, value := range values {
				specification[key] = value
			}
			raw, _ := json.Marshal(specification)
			column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, string(raw), schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
			bad := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, column}}}
			bad, err = New().Normalize(context.Background(), bad)
			if err != nil {
				t.Fatal(err)
			}
			if rendered, renderErr := RenderDocument(context.Background(), bad, nil); renderErr == nil || len(rendered) != 0 {
				t.Fatalf("rendered=%+v err=%v", rendered, renderErr)
			}
		})
	}
}

func TestUnchangedIdentityDoesNotBlockUnrelatedColumn(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	id := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, `{"identity":"a","not_null":true,"ordinal":1,"type":"bigint"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, id}}}
	label := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "label", Parent: table.ID}, `{"not_null":false,"ordinal":2,"type":"text"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, id, label}}}
	changes, err := schema.Diff(current, desired, schema.DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err != nil || len(out) != 1 || !strings.Contains(out[0].SQL, "ADD COLUMN") {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestRenderDocumentQuotesAndOrders(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: `Odd"Schema`}, `{}`)
	view := renderResource(schema.KindView, schema.Name{Schema: s.Name.Name, Name: `a"b`, Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	column := projection(view, "value", "integer")
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{column, view, s}}}
	out, err := RenderDocument(context.Background(), doc, nil)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{`CREATE SCHEMA "Odd""Schema";`, `CREATE VIEW "Odd""Schema"."a""b" AS SELECT 1 AS value;`}
	var executable []plugin.Statement
	for _, statement := range out {
		if statement.Kind != plugin.StatementTopology {
			executable = append(executable, statement)
		}
	}
	if len(executable) != len(want) {
		t.Fatalf("out=%+v", out)
	}
	for i := range want {
		if executable[i].SQL != want[i] {
			t.Errorf("%d got %q want %q", i, executable[i].SQL, want[i])
		}
	}
}

func TestRenderDocumentGolden(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "widgets", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	column := projection(view, "value", "integer")
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{column, view, s}}}
	out, err := RenderDocument(context.Background(), doc, nil)
	if err != nil {
		t.Fatal(err)
	}
	var lines []string
	for i := range out {
		if out[i].Kind != plugin.StatementTopology {
			lines = append(lines, out[i].SQL)
		}
	}
	actual := strings.Join(lines, "\n") + "\n"
	expected, err := os.ReadFile("testdata/render_document.golden.sql")
	if err != nil {
		t.Fatal(err)
	}
	if actual != string(expected) {
		t.Fatalf("golden mismatch\nactual:\n%s\nexpected:\n%s", actual, expected)
	}
}

func TestConcurrentRenderingUsesNonTransactionalPhase(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "users", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	idx := renderResource(schema.KindIndex, schema.Name{Schema: "public", Name: "users_email_idx", Parent: table.ID}, `{"definition":"(email)"}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	empty := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{}}}
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, idx}}}
	changes, _ := schema.Diff(empty, desired, schema.DiffOptions{})
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: empty, Desired: desired, Options: map[string]string{"concurrent_indexes": "true"}})
	concurrent := 0
	for _, statement := range out {
		if strings.Contains(statement.SQL, "CONCURRENTLY") && !statement.Transactional {
			concurrent++
		}
	}
	if err != nil || concurrent != 1 {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestMaterializedViewAlterRequiresExplicitRebuild(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	before := renderResource(schema.KindMaterializedView, schema.Name{Schema: "public", Name: "users_mv", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	after := before
	after.Spec = json.RawMessage(`{"definition":"SELECT 2 AS value"}`)
	column := projection(before, "value", "integer")
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{s, before, column}}}
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{s, after, column}}}
	changes, _ := schema.Diff(current, desired, schema.DiffOptions{})
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err == nil || len(out) != 0 {
		t.Fatalf("out=%+v err=%v", out, err)
	}
	out, err = New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired, Options: map[string]string{"allow_rebuild": "true"}})
	if err != nil || len(out) != 2 {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestCreateHelpersRemainDeterministicForInspectedKinds(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "users", Parent: s.ID}, `{}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	resources := map[string]schema.Resource{s.ID: s, table.ID: table}
	cases := []schema.Resource{
		s,
		renderResource(schema.KindExtension, schema.Name{Schema: "app", Name: "hstore", Parent: s.ID}, `{"version":"1.8"}`),
		renderResource(schema.KindEnum, schema.Name{Schema: "app", Name: "status", Parent: s.ID}, `{"values":["new"]}`),
		renderResource(schema.KindDomain, schema.Name{Schema: "app", Name: "positive", Parent: s.ID}, `{"base_type":"integer","not_null":true}`),
		renderResource(schema.KindComposite, schema.Name{Schema: "app", Name: "address", Parent: s.ID}, `{"attributes":[{"name":"zip","type":"integer"}]}`),
		renderResource(schema.KindSequence, schema.Name{Schema: "app", Name: "seq", Parent: s.ID}, `{"start":1,"increment":1}`),
		table,
		renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, `{"type":"bigint"}`),
		renderResource(schema.KindPrimaryKey, schema.Name{Schema: "app", Name: "users_pkey", Parent: table.ID}, `{"definition":"PRIMARY KEY (id)"}`),
		renderResource(schema.KindUniqueConstraint, schema.Name{Schema: "app", Name: "users_id_key", Parent: table.ID}, `{"definition":"UNIQUE (id)"}`),
		renderResource(schema.KindCheckConstraint, schema.Name{Schema: "app", Name: "users_id_check", Parent: table.ID}, `{"definition":"CHECK (id > 0)"}`),
		renderResource(schema.KindForeignKey, schema.Name{Schema: "app", Name: "users_parent_fkey", Parent: table.ID}, `{"definition":"FOREIGN KEY (id) REFERENCES app.users(id)"}`),
		renderResource(schema.KindIndex, schema.Name{Schema: "app", Name: "users_idx", Parent: table.ID}, `{"definition":"(id)"}`),
		renderResource(schema.KindView, schema.Name{Schema: "app", Name: "user_view", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`),
		renderResource(schema.KindMaterializedView, schema.Name{Schema: "app", Name: "user_mv", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`),
	}
	for _, r := range cases {
		resources[r.ID] = r
		if r.Kind == schema.KindView || r.Kind == schema.KindMaterializedView {
			column := projection(r, "value", "integer")
			resources[column.ID] = column
		}
	}
	for _, r := range cases {
		options := map[string]string{"extension_allowlist": "hstore"}
		if _, err := renderCreate(r, resources, options); err != nil {
			t.Errorf("create %s: %v", r.Kind, err)
		}
	}
}

func TestNativeViewFragmentsRejectInjection(t *testing.T) {
	for _, fragment := range []string{"SELECT 1; DROP TABLE users", "SELECT 1 -- hidden", "SELECT /* hidden */ 1", "SELECT $tag$payload$tag$"} {
		t.Run(fragment, func(t *testing.T) {
			r := renderResource(schema.KindView, schema.Name{Schema: "public", Name: "v"}, `{}`)
			raw, _ := json.Marshal(map[string]string{"definition": fragment})
			r.Spec = raw
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: r.ID, After: &r}}}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}

func TestManagedMetadataAndIdentifierControlsFailClosed(t *testing.T) {
	cases := []schema.Resource{}
	s := renderResource(schema.KindSchema, schema.Name{Name: "app\nDROP"}, `{}`)
	cases = append(cases, s)
	catalog := renderResource(schema.KindSchema, schema.Name{Catalog: "other", Name: "app"}, `{}`)
	cases = append(cases, catalog)
	annotated := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	annotated.Annotations = map[string]string{"future": "not rendered"}
	cases = append(cases, annotated)
	extra := renderResource(schema.KindSchema, schema.Name{Name: "extra"}, `{}`)
	extra.Extra = map[string]json.RawMessage{"future": json.RawMessage(`true`)}
	cases = append(cases, extra)
	nameExtra := renderResource(schema.KindSchema, schema.Name{Name: "name_extra"}, `{}`)
	nameExtra.Name.Extra = map[string]json.RawMessage{"future": json.RawMessage(`true`)}
	cases = append(cases, nameExtra)
	dependencyExtra := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "dependency_extra", Parent: "schema:missing"}, `{}`, schema.Dependency{Target: "schema:missing", Type: schema.DependencyContains, Extra: map[string]json.RawMessage{"future": json.RawMessage(`true`)}})
	cases = append(cases, dependencyExtra)
	for _, persistence := range []string{"t", "u"} {
		cases = append(cases, renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "t_" + persistence}, `{"partitioned":false,"persistence":"`+persistence+`","row_security":false,"force_row_security":false}`))
	}
	wrongType := renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "wrong_type"}, `{"partitioned":"false","persistence":1,"row_security":false,"force_row_security":false}`)
	cases = append(cases, wrongType)
	cases = append(cases, renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "partitioned"}, `{"partitioned":true,"persistence":"p","row_security":false,"force_row_security":false}`))
	for _, r := range cases {
		change := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: r.ID, After: &r}}}
		out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: change})
		if err == nil || len(out) != 0 {
			t.Fatalf("resource=%+v out=%+v err=%v", r, out, err)
		}
	}
}

func TestManagedCommentsRenderCreateAndLifecycle(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "label", Parent: table.ID}, `{"type":"text","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	enum := renderResource(schema.KindEnum, schema.Name{Schema: "app", Name: "state", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	domain := renderResource(schema.KindDomain, schema.Name{Schema: "app", Name: "positive", Parent: ns.ID}, `{"base_type":"integer","not_null":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	sequence := renderResource(schema.KindSequence, schema.Name{Schema: "app", Name: "widget_seq", Parent: ns.ID}, `{"start":1,"increment":1,"min":1,"max":9223372036854775807,"cache":1,"cycle":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "widget_view", Parent: ns.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	viewColumn := projection(view, "value", "integer")
	materialized := renderResource(schema.KindMaterializedView, schema.Name{Schema: "app", Name: "widget_mv", Parent: ns.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	materializedColumn := projection(materialized, "value", "integer")
	resources := []schema.Resource{ns, table, column, enum, domain, sequence, view, viewColumn, materialized, materializedColumn}
	for i := range resources {
		resources[i].Annotations = map[string]string{"comment": "quote ' snowman ☃\nline; DROP TABLE app.widgets; --"}
	}
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: resources}}
	out, err := RenderDocument(context.Background(), doc, nil)
	if err != nil {
		t.Fatal(err)
	}
	joined := ""
	for _, statement := range out {
		joined += statement.SQL + "\n"
	}
	for _, target := range []string{
		`COMMENT ON SCHEMA "app"`, `COMMENT ON TABLE "app"."widgets"`, `COMMENT ON COLUMN "app"."widgets"."label"`,
		`COMMENT ON TYPE "app"."state"`, `COMMENT ON DOMAIN "app"."positive"`, `COMMENT ON SEQUENCE "app"."widget_seq"`,
		`COMMENT ON VIEW "app"."widget_view"`, `COMMENT ON COLUMN "app"."widget_view"."value"`,
		`COMMENT ON MATERIALIZED VIEW "app"."widget_mv"`, `COMMENT ON COLUMN "app"."widget_mv"."value"`,
	} {
		if !strings.Contains(joined, target) {
			t.Errorf("missing %s in:\n%s", target, joined)
		}
	}
	if !strings.Contains(joined, `quote '' snowman ☃`+"\n"+`line; DROP TABLE app.widgets; --'`) {
		t.Fatalf("comment was not safely encoded as one literal:\n%s", joined)
	}

	current := doc
	current.Graph.Resources = append([]schema.Resource(nil), doc.Graph.Resources...)
	desired := doc
	desired.Graph.Resources = append([]schema.Resource(nil), doc.Graph.Resources...)
	current.Graph.Resources[0].Annotations = map[string]string{"comment": "old"}
	desired.Graph.Resources[0].Annotations = map[string]string{"comment": "new"}
	changes, err := schema.Diff(current, desired, schema.DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	changed, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err != nil || len(changed) != 1 || changed[0].SQL != `COMMENT ON SCHEMA "app" IS 'new';` {
		t.Fatalf("comment change out=%+v err=%v", changed, err)
	}
	current = desired
	desired.Graph.Resources = append([]schema.Resource(nil), desired.Graph.Resources...)
	desired.Graph.Resources[0].Annotations = nil
	changes, err = schema.Diff(current, desired, schema.DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	removed, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err != nil || len(removed) != 1 || removed[0].SQL != `COMMENT ON SCHEMA "app" IS NULL;` {
		t.Fatalf("comment removal out=%+v err=%v", removed, err)
	}
}

func TestUnchangedManagedCommentsDoNotBlockUnrelatedChange(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	ns.Annotations = map[string]string{"comment": "namespace"}
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	table.Annotations = map[string]string{"comment": "table"}
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table}}}
	column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "label", Parent: table.ID}, `{"type":"text","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, column}}}
	changes, err := schema.Diff(current, desired, schema.DiffOptions{})
	if err != nil {
		t.Fatal(err)
	}
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err != nil || len(out) != 1 || !strings.Contains(out[0].SQL, "ADD COLUMN") {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestColumnOrdinalTopologyRetainsCommentUpdate(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	before := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "label", Parent: table.ID}, `{"type":"text","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	before.Annotations = map[string]string{"comment": "before"}
	after := before
	after.Spec = json.RawMessage(`{"type":"text","not_null":false,"ordinal":2}`)
	after.Annotations = map[string]string{"comment": "after"}
	change := schema.Change{ID: "c", Operation: schema.OperationAlter, ResourceID: after.ID, Before: &before, After: &after}
	out, err := renderChange(change, map[string]schema.Resource{ns.ID: ns, table.ID: table, after.ID: after}, nil)
	if err != nil || len(out) != 2 || out[0].Kind != plugin.StatementTopology || out[1].SQL != `COMMENT ON COLUMN "app"."widgets"."label" IS 'after';` {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestManagedResourcesRequireCanonicalIdentityAndDependencies(t *testing.T) {
	app := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	other := renderResource(schema.KindSchema, schema.Name{Name: "other"}, `{}`)
	base := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: app.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: app.ID, Type: schema.DependencyContains})
	cases := map[string]schema.Resource{}
	wrongParent := base
	wrongParent.Name.Parent = other.ID
	cases["schema parent mismatch"] = wrongParent
	missingContains := base
	missingContains.Dependencies = nil
	cases["missing contains"] = missingContains
	extraDependency := base
	extraDependency.Dependencies = append(extraDependency.Dependencies, schema.Dependency{Target: other.ID, Type: schema.DependencyReferences})
	cases["ignored reference"] = extraDependency
	for name, table := range cases {
		t.Run(name, func(t *testing.T) {
			doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{app, other, table}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: table.ID, After: &table}}}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: doc})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
	schemaWithDependency := app
	schemaWithDependency.Dependencies = []schema.Dependency{{Target: other.ID, Type: schema.DependencyReferences}}
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{other, schemaWithDependency}}}
	changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: app.ID, After: &schemaWithDependency}}}
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: doc})
	if err == nil || len(out) != 0 {
		t.Fatalf("schema dependency out=%+v err=%v", out, err)
	}
}

func TestRenderedDependenciesMustExactlyMatchSemantics(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	unrelated := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "other", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	tableColumn := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, `{"type":"integer","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	base := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "v", Parent: ns.ID}, `{"definition":"SELECT id FROM app.widgets"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains}, schema.Dependency{Target: table.ID, Type: schema.DependencyReferences})
	for name, mutate := range map[string]func(*schema.Resource){
		"missing actual reference": func(view *schema.Resource) { view.Dependencies = view.Dependencies[:1] },
		"extra unrelated reference": func(view *schema.Resource) {
			view.Dependencies = append(view.Dependencies, schema.Dependency{Target: unrelated.ID, Type: schema.DependencyReferences})
		},
	} {
		t.Run(name, func(t *testing.T) {
			view := base
			view.Dependencies = append([]schema.Dependency(nil), base.Dependencies...)
			mutate(&view)
			column := projection(view, "id", "integer")
			doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, tableColumn, unrelated, view, column}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: view.ID, After: &view}}}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: doc})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
	status := renderResource(schema.KindEnum, schema.Name{Schema: "app", Name: "status", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	otherType := renderResource(schema.KindEnum, schema.Name{Schema: "app", Name: "other_status", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	baseColumn := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "status", Parent: table.ID}, `{"type":"app.status","not_null":false,"ordinal":2}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains}, schema.Dependency{Target: status.ID, Type: schema.DependencyUses})
	for name, mutate := range map[string]func(*schema.Resource){
		"missing type use": func(column *schema.Resource) { column.Dependencies = column.Dependencies[:1] },
		"extra type use": func(column *schema.Resource) {
			column.Dependencies = append(column.Dependencies, schema.Dependency{Target: otherType.ID, Type: schema.DependencyUses})
		},
	} {
		t.Run(name, func(t *testing.T) {
			column := baseColumn
			column.Dependencies = append([]schema.Dependency(nil), baseColumn.Dependencies...)
			mutate(&column)
			doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, tableColumn, status, otherType, column}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: column.ID, After: &column}}}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: doc})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}

func TestColumnTypeAlterAllowsOnlyKnownSafeCasts(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	before := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "value", Parent: table.ID}, `{"type":"text","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	for name, typ := range map[string]string{"unsafe text integer": "integer", "safe text varchar is assignment-direction unsafe": "character varying"} {
		t.Run(name, func(t *testing.T) {
			after := before
			after.Spec = json.RawMessage(`{"type":"` + typ + `","not_null":false,"ordinal":1}`)
			current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, before}}}
			desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, after}}}
			changes, _ := schema.Diff(current, desired, schema.DiffOptions{})
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}

func TestColumnOrdinalTransitionsRequirePhysicalProof(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	column := func(name string, ordinal int) schema.Resource {
		return renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: name, Parent: table.ID}, fmt.Sprintf(`{"type":"text","not_null":false,"ordinal":%d}`, ordinal), schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	}
	a, b := column("a", 1), column("b", 2)
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, a, b}}}
	for name, resources := range map[string][]schema.Resource{
		"middle insertion": {ns, table, a, column("c", 2), column("b", 3)},
		"pure reorder":     {ns, table, column("b", 1), column("a", 2)},
	} {
		t.Run(name, func(t *testing.T) {
			desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: resources}}
			changes, _ := schema.Diff(current, desired, schema.DiffOptions{})
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
			if err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
	mixedB := column("b", 1)
	mixedB.Spec = json.RawMessage(`{"type":"text","not_null":true,"ordinal":1}`)
	mixed := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, mixedB}}}
	changes, _ := schema.Diff(current, mixed, schema.DiffOptions{})
	if out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: mixed}); err == nil || len(out) != 0 {
		t.Fatalf("mixed shift out=%+v err=%v", out, err)
	}
}

func TestNestedViewDependenciesRequireExactCapturedGraph(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	a := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "a", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	b := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "b", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	for name, test := range map[string]struct {
		deps    []schema.Dependency
		allowed bool
	}{
		"missing nested relation":  {deps: []schema.Dependency{{Target: ns.ID, Type: schema.DependencyContains}, {Target: a.ID, Type: schema.DependencyReferences}}},
		"declared nested relation": {deps: []schema.Dependency{{Target: ns.ID, Type: schema.DependencyContains}, {Target: a.ID, Type: schema.DependencyReferences}, {Target: b.ID, Type: schema.DependencyReferences}}, allowed: true},
	} {
		t.Run(name, func(t *testing.T) {
			view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "v", Parent: ns.ID}, `{"definition":"SELECT id FROM app.a WHERE EXISTS (SELECT 1 FROM app.b)"}`, test.deps...)
			projection := projection(view, "id", "integer")
			desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, a, b, view, projection}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: view.ID, After: &view}}}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: desired})
			if test.allowed && (err != nil || len(out) != 1) {
				t.Fatalf("out=%+v err=%v", out, err)
			}
			if !test.allowed && (err == nil || len(out) != 0) {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
	cte := renderResource(schema.KindMaterializedView, schema.Name{Schema: "app", Name: "cte_v", Parent: ns.ID}, `{"definition":"WITH source AS (SELECT id FROM app.a) SELECT id FROM source"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains}, schema.Dependency{Target: a.ID, Type: schema.DependencyReferences})
	cteProjection := projection(cte, "id", "integer")
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, a, cte, cteProjection}}}
	changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "cte", Operation: schema.OperationCreate, ResourceID: cte.ID, After: &cte}}}
	if out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: desired}); err != nil || len(out) != 1 {
		t.Fatalf("CTE out=%+v err=%v", out, err)
	}
}

func TestMaterializedViewProjectionTypeDependenciesAreExact(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	provider := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "provider", Parent: ns.ID}, `{"values":["aws","gcp"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	source := renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "blocks", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	sourceProvider := renderResource(schema.KindColumn, schema.Name{Schema: "public", Name: "provider", Parent: source.ID}, `{"type":"provider","not_null":false,"ordinal":1}`, schema.Dependency{Target: source.ID, Type: schema.DependencyContains}, schema.Dependency{Target: provider.ID, Type: schema.DependencyUses})
	view := renderResource(schema.KindMaterializedView, schema.Name{Schema: "public", Name: "block_health_summary", Parent: ns.ID}, `{"definition":"SELECT provider, count(*)::bigint AS total FROM public.blocks GROUP BY provider"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains}, schema.Dependency{Target: source.ID, Type: schema.DependencyReferences})
	projectionProvider := projection(view, "provider", "provider")
	projectionProvider.Dependencies = append(projectionProvider.Dependencies, schema.Dependency{Target: provider.ID, Type: schema.DependencyUses})
	total := projection(view, "total", "bigint")
	total.Spec = json.RawMessage(`{"type":"bigint","not_null":false,"ordinal":2}`)
	resources := []schema.Resource{ns, provider, source, sourceProvider, view, projectionProvider, total}
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: resources}}
	if statements, err := RenderDocument(context.Background(), doc, nil); err != nil || len(statements) == 0 {
		t.Fatalf("projection type-use statements=%+v err=%v", statements, err)
	}
	for name, mutate := range map[string]func(*schema.Resource){
		"missing type use": func(column *schema.Resource) { column.Dependencies = column.Dependencies[:1] },
		"duplicate type use": func(column *schema.Resource) {
			column.Dependencies = append(column.Dependencies, schema.Dependency{Target: provider.ID, Type: schema.DependencyUses})
		},
		"reference instead of use": func(column *schema.Resource) {
			column.Dependencies[1].Type = schema.DependencyReferences
		},
	} {
		t.Run(name, func(t *testing.T) {
			bad := projectionProvider
			bad.Dependencies = append([]schema.Dependency(nil), projectionProvider.Dependencies...)
			mutate(&bad)
			badResources := append([]schema.Resource(nil), resources...)
			badResources[5] = bad
			if statements, err := RenderDocument(context.Background(), schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: badResources}}, nil); err == nil || len(statements) != 0 {
				t.Fatalf("statements=%+v err=%v", statements, err)
			}
		})
	}
}

func TestTableQueryExpressionFailsClosed(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "b", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "v", Parent: ns.ID}, `{"definition":"TABLE app.b"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains}, schema.Dependency{Target: table.ID, Type: schema.DependencyReferences})
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, view}}}
	changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: view.ID, After: &view}}}
	if out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: desired}); err == nil || len(out) != 0 {
		t.Fatalf("out=%+v err=%v", out, err)
	}
}

func TestCanonicalUDTUsesAcceptsQuotedUnqualifiedAndArrays(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	status := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "status", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	mood := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "Mood", Parent: ns.ID}, `{"values":["good"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	resources := map[string]schema.Resource{ns.ID: ns, table.ID: table, status.ID: status, mood.ID: mood}
	for name, fixture := range map[string]struct{ typ, target string }{
		"public unqualified array": {"status[]", status.ID},
		"quoted unqualified array": {`"Mood"[]`, mood.ID},
		"quoted qualified scalar":  {`public."Mood"`, mood.ID},
	} {
		t.Run(name, func(t *testing.T) {
			column := renderResource(schema.KindColumn, schema.Name{Schema: "public", Name: "value", Parent: table.ID}, `{"type":"`+strings.ReplaceAll(fixture.typ, `"`, `\"`)+`","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains}, schema.Dependency{Target: fixture.target, Type: schema.DependencyUses})
			if err := validateSemanticDependencies(column, resources); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestNormalizeCanonicalizesTypeFromUsesTarget(t *testing.T) {
	public := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	mixed := renderResource(schema.KindSchema, schema.Name{Name: "Mixed"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "Mixed", Name: "widgets", Parent: mixed.ID}, `{}`, schema.Dependency{Target: mixed.ID, Type: schema.DependencyContains})
	publicType := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "status", Parent: public.ID}, `{"values":["new"]}`, schema.Dependency{Target: public.ID, Type: schema.DependencyContains})
	mixedType := renderResource(schema.KindEnum, schema.Name{Schema: "Mixed", Name: "Mood", Parent: mixed.ID}, `{"values":["good"]}`, schema.Dependency{Target: mixed.ID, Type: schema.DependencyContains})
	columns := []schema.Resource{
		renderResource(schema.KindColumn, schema.Name{Schema: "Mixed", Name: "a", Parent: table.ID}, `{"type":"public.status[][]","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains}, schema.Dependency{Target: publicType.ID, Type: schema.DependencyUses}),
		renderResource(schema.KindColumn, schema.Name{Schema: "Mixed", Name: "b", Parent: table.ID}, `{"type":"\"Mood\"[][]","not_null":false,"ordinal":2}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains}, schema.Dependency{Target: mixedType.ID, Type: schema.DependencyUses}),
	}
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: append([]schema.Resource{public, mixed, table, publicType, mixedType}, columns...)}}
	normalized, err := New().Normalize(context.Background(), doc)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{"a": "status[]", "b": `"Mixed"."Mood"[]`}
	for _, r := range normalized.Graph.Resources {
		if expected := want[r.Name.Name]; expected != "" && stringValue(spec(r), "type") != expected {
			t.Errorf("%s type=%q want=%q", r.Name.Name, stringValue(spec(r), "type"), expected)
		}
	}
}

func TestNormalizeRejectsTypeUsesMismatch(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "public", Name: "widgets", Parent: ns.ID}, `{}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	status := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "status", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	other := renderResource(schema.KindEnum, schema.Name{Schema: "public", Name: "other", Parent: ns.ID}, `{"values":["new"]}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	for name, fixture := range map[string]struct{ typ, target string }{
		"builtin with enum use": {"integer", status.ID},
		"unrelated UDT":         {"status", other.ID},
		"mismatched array UDT":  {"status[][]", other.ID},
	} {
		t.Run(name, func(t *testing.T) {
			column := renderResource(schema.KindColumn, schema.Name{Schema: "public", Name: "value", Parent: table.ID}, fmt.Sprintf(`{"type":%q,"not_null":false,"ordinal":1}`, fixture.typ), schema.Dependency{Target: table.ID, Type: schema.DependencyContains}, schema.Dependency{Target: fixture.target, Type: schema.DependencyUses})
			doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, status, other, column}}}
			if normalized, err := New().Normalize(context.Background(), doc); err == nil || len(normalized.Graph.Resources) != 0 {
				t.Fatalf("normalized=%+v err=%v", normalized, err)
			}
		})
	}
}

func TestDirectProjectionQualifierAndWildcardRules(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "a", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "id", Parent: table.ID}, `{"type":"integer","not_null":false,"ordinal":1}`, schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
	for name, definition := range map[string]string{"foreign qualifier": "SELECT b.id FROM app.a", "mixed wildcard": "SELECT *, id FROM app.a"} {
		t.Run(name, func(t *testing.T) {
			view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "v", Parent: ns.ID}, `{"definition":"`+definition+`"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains}, schema.Dependency{Target: table.ID, Type: schema.DependencyReferences})
			desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, column, view}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: view.ID, After: &view}}}
			if out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: desired}); err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}

func TestCoreColumnGrammarRejectsClauseSmugglingAndNoncanonicalForms(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	for name, fixture := range map[string]struct{ typ, def string }{
		"embedded not null": {"text NOT NULL", ""}, "collation": {"text COLLATE C", ""}, "constraint": {"integer CHECK (value>0)", ""},
		"char variant": {"char(4)", ""}, "decimal variant": {"decimal(10,2)", ""}, "noncanonical precision": {"timestamp(03)", ""}, "precision range": {"timestamp(7)", ""},
		"zero length": {"character varying(0)", ""}, "modifier whitespace": {"numeric(10, 2)", ""}, "scale range": {"numeric(10,11)", ""}, "array keyword": {"integer ARRAY", ""},
		"function default": {"integer", "nextval('x')"},
	} {
		t.Run(name, func(t *testing.T) {
			spec := map[string]any{"type": fixture.typ, "not_null": false, "ordinal": 1}
			if fixture.def != "" {
				spec["default"] = fixture.def
			}
			raw, _ := json.Marshal(spec)
			column := renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: "value", Parent: table.ID}, string(raw), schema.Dependency{Target: table.ID, Type: schema.DependencyContains})
			desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, table, column}}}
			changes := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{{ID: "c", Operation: schema.OperationCreate, ResourceID: column.ID, After: &column}}}
			if out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Desired: desired}); err == nil || len(out) != 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}

func TestCoreColumnGrammarRendersCanonicalTypeModifiers(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "widgets", Parent: ns.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	types := []string{"character varying(255)", "character varying(8)[]", "numeric(10)", "numeric(10,2)", "timestamp(0)", "timestamp(3)", "timestamptz(6)"}
	resources := []schema.Resource{ns, table}
	for index, typ := range types {
		spec := map[string]any{"type": typ, "not_null": false, "ordinal": index + 1}
		if index == 0 {
			spec["default"] = "'widget'"
		}
		raw, _ := json.Marshal(spec)
		resources = append(resources, renderResource(schema.KindColumn, schema.Name{Schema: "app", Name: fmt.Sprintf("value_%d", index), Parent: table.ID}, string(raw), schema.Dependency{Target: table.ID, Type: schema.DependencyContains}))
	}
	doc := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: resources}}
	out, err := RenderDocument(context.Background(), doc, nil)
	if err != nil {
		t.Fatal(err)
	}
	joined := ""
	for _, statement := range out {
		joined += statement.SQL + "\n"
	}
	for _, typ := range types {
		if !strings.Contains(joined, typ) {
			t.Errorf("rendered SQL missing type %q:\n%s", typ, joined)
		}
	}
}

func TestViewAlterOutputShapePolicy(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	view := renderResource(schema.KindView, schema.Name{Schema: "public", Name: "v", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	column := projection(view, "value", "integer")
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{s, view, column}}}
	same := view
	same.Spec = json.RawMessage(`{"definition":"SELECT 2 AS value"}`)
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{s, same, column}}}
	changes, _ := schema.Diff(current, desired, schema.DiffOptions{})
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err != nil || len(out) != 1 {
		t.Fatalf("same shape out=%+v err=%v", out, err)
	}
	for name, mutate := range map[string]func(*schema.Resource, *schema.Resource){"name": func(v, c *schema.Resource) {
		v.Spec = json.RawMessage(`{"definition":"SELECT 2 AS other"}`)
		c.Name.Name = "other"
		c.ID = schema.StableID(c.Kind, c.Name)
	}, "type": func(v, c *schema.Resource) {
		v.Spec = json.RawMessage(`{"definition":"SELECT 'x'::text AS value"}`)
		c.Spec = json.RawMessage(`{"not_null":false,"ordinal":1,"type":"text"}`)
	}} {
		t.Run(name, func(t *testing.T) {
			v, c := view, column
			mutate(&v, &c)
			target := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{s, v, c}}}
			cs, _ := schema.Diff(current, target, schema.DiffOptions{})
			result, e := New().Render(context.Background(), plugin.RenderRequest{Changes: cs, Current: current, Desired: target})
			if e == nil || len(result) != 0 {
				t.Fatalf("out=%+v err=%v", result, e)
			}
		})
	}
}

func TestIndependentOrMalformedProjectionChangesFailClosed(t *testing.T) {
	ns := renderResource(schema.KindSchema, schema.Name{Name: "public"}, `{}`)
	view := renderResource(schema.KindView, schema.Name{Schema: "public", Name: "v", Parent: ns.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: ns.ID, Type: schema.DependencyContains})
	column := projection(view, "value", "integer")
	current := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, view}}}
	desired := schema.Document{Version: schema.SchemaVersion, Graph: schema.Graph{Resources: []schema.Resource{ns, view, column}}}
	changes, _ := schema.Diff(current, desired, schema.DiffOptions{})
	out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err == nil || len(out) != 0 {
		t.Fatalf("independent out=%+v err=%v", out, err)
	}
	bad := column
	bad.Spec = json.RawMessage(`{"future":true,"not_null":false,"ordinal":1,"type":"integer"}`)
	desired.Graph.Resources = []schema.Resource{ns, view, bad}
	changes, _ = schema.Diff(current, desired, schema.DiffOptions{})
	out, err = New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err == nil || len(out) != 0 {
		t.Fatalf("malformed out=%+v err=%v", out, err)
	}
	bad = column
	bad.Dependencies = []schema.Dependency{{Target: view.ID, Type: schema.DependencyReferences}}
	desired.Graph.Resources = []schema.Resource{ns, view, bad}
	changes, _ = schema.Diff(current, desired, schema.DiffOptions{})
	out, err = New().Render(context.Background(), plugin.RenderRequest{Changes: changes, Current: current, Desired: desired})
	if err == nil || len(out) != 0 {
		t.Fatalf("bad dependency out=%+v err=%v", out, err)
	}
}

func TestManagedLifecycleMatrix(t *testing.T) {
	s := renderResource(schema.KindSchema, schema.Name{Name: "app"}, `{}`)
	s2 := renderResource(schema.KindSchema, schema.Name{Name: "app2"}, `{}`)
	table := renderResource(schema.KindTable, schema.Name{Schema: "app", Name: "users", Parent: s.ID}, `{"partitioned":false,"persistence":"p","row_security":false,"force_row_security":false}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	table2 := table
	table2.Spec = json.RawMessage(`{"partitioned":false,"persistence":"p","row_security":true,"force_row_security":false}`)
	tableRenamed := table
	tableRenamed.Name.Name = "users2"
	tableRenamed.ID = schema.StableID(tableRenamed.Kind, tableRenamed.Name)
	view := renderResource(schema.KindView, schema.Name{Schema: "app", Name: "v", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	view2 := view
	view2.Spec = json.RawMessage(`{"definition":"SELECT 2 AS value"}`)
	viewRenamed := view
	viewRenamed.Name.Name = "v2"
	viewRenamed.ID = schema.StableID(viewRenamed.Kind, viewRenamed.Name)
	mv := renderResource(schema.KindMaterializedView, schema.Name{Schema: "app", Name: "mv", Parent: s.ID}, `{"definition":"SELECT 1 AS value"}`, schema.Dependency{Target: s.ID, Type: schema.DependencyContains})
	mv2 := mv
	mv2.Spec = json.RawMessage(`{"definition":"SELECT 2 AS value"}`)
	mvRenamed := mv
	mvRenamed.Name.Name = "mv2"
	mvRenamed.ID = schema.StableID(mvRenamed.Kind, mvRenamed.Name)
	vcol := projection(view, "value", "integer")
	mvcol := projection(mv, "value", "integer")
	vcolRenamed := projection(viewRenamed, "value", "integer")
	mvcolRenamed := projection(mvRenamed, "value", "integer")
	resources := map[string]schema.Resource{s.ID: s, s2.ID: s2, table.ID: table, tableRenamed.ID: tableRenamed, view.ID: view, viewRenamed.ID: viewRenamed, mv.ID: mv, mvRenamed.ID: mvRenamed, vcol.ID: vcol, mvcol.ID: mvcol, vcolRenamed.ID: vcolRenamed, mvcolRenamed.ID: mvcolRenamed}
	tests := []struct {
		name    string
		change  schema.Change
		options map[string]string
	}{{"schema create", schema.Change{ID: "c1", Operation: schema.OperationCreate, ResourceID: s.ID, After: &s}, nil}, {"schema drop", schema.Change{ID: "c2", Operation: schema.OperationDrop, ResourceID: s.ID, Before: &s}, nil}, {"schema rename", schema.Change{ID: "c3", Operation: schema.OperationRename, ResourceID: s2.ID, Before: &s, After: &s2}, nil}, {"table create", schema.Change{ID: "c4", Operation: schema.OperationCreate, ResourceID: table.ID, After: &table}, nil}, {"table drop", schema.Change{ID: "c5", Operation: schema.OperationDrop, ResourceID: table.ID, Before: &table}, nil}, {"table alter", schema.Change{ID: "c6", Operation: schema.OperationAlter, ResourceID: table.ID, Before: &table, After: &table2}, nil}, {"table rename", schema.Change{ID: "c11", Operation: schema.OperationRename, ResourceID: tableRenamed.ID, Before: &table, After: &tableRenamed}, nil}, {"view create", schema.Change{ID: "c7", Operation: schema.OperationCreate, ResourceID: view.ID, After: &view}, nil}, {"view drop", schema.Change{ID: "c8", Operation: schema.OperationDrop, ResourceID: view.ID, Before: &view}, nil}, {"view alter", schema.Change{ID: "c9", Operation: schema.OperationAlter, ResourceID: view.ID, Before: &view, After: &view2}, nil}, {"view rename", schema.Change{ID: "c12", Operation: schema.OperationRename, ResourceID: viewRenamed.ID, Before: &view, After: &viewRenamed}, nil}, {"mv create", schema.Change{ID: "c13", Operation: schema.OperationCreate, ResourceID: mv.ID, After: &mv}, nil}, {"mv drop", schema.Change{ID: "c14", Operation: schema.OperationDrop, ResourceID: mv.ID, Before: &mv}, nil}, {"mv rename", schema.Change{ID: "c15", Operation: schema.OperationRename, ResourceID: mvRenamed.ID, Before: &mv, After: &mvRenamed}, nil}, {"mv rebuild", schema.Change{ID: "c10", Operation: schema.OperationAlter, ResourceID: mv.ID, Before: &mv, After: &mv2}, map[string]string{"allow_rebuild": "true"}}}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			cs := schema.ChangeSet{Version: schema.ChangeVersion, Changes: []schema.Change{tc.change}}
			docResources := mapValues(resources)
			if tc.name == "schema rename" {
				docResources = []schema.Resource{s, s2}
			}
			out, err := New().Render(context.Background(), plugin.RenderRequest{Changes: cs, Current: schema.Document{Graph: schema.Graph{Resources: docResources}}, Desired: schema.Document{Graph: schema.Graph{Resources: docResources}}, Options: tc.options})
			if err != nil || len(out) == 0 {
				t.Fatalf("out=%+v err=%v", out, err)
			}
		})
	}
}
func mapValues(values map[string]schema.Resource) []schema.Resource {
	out := make([]schema.Resource, 0, len(values))
	for _, r := range values {
		out = append(out, r)
	}
	return out
}
