#!/usr/bin/env bash
set -euo pipefail

version="${1:-}"
assets="${2:-}"
source_root="${3:-.}"
check_only="${4:-}"
repository="${TERRAFORM_PROVIDER_REPOSITORY:-stigenai/terraform-provider-autosql}"

case "$version" in v[0-9]*.[0-9]*.[0-9]*) ;; *) echo 'version must be vMAJOR.MINOR.PATCH' >&2; exit 2;; esac
test -d "$assets" || { echo 'provider asset directory is required' >&2; exit 2; }
test -f "$assets/terraform-provider-autosql_SHA256SUMS" || { echo 'provider checksums are required' >&2; exit 2; }
test -f "$assets/terraform-provider-autosql_SHA256SUMS.sig" || { echo 'provider checksum signature is required' >&2; exit 2; }
find "$assets" -maxdepth 1 -name 'terraform-provider-autosql_*.zip' -print -quit | grep -q . || { echo 'provider archives are required' >&2; exit 2; }
if test "$check_only" = --check; then exit 0; fi

test -n "${GH_TOKEN:-}" || { echo 'GH_TOKEN is required' >&2; exit 2; }
for command in gh git tar; do command -v "$command" >/dev/null || { echo "$command is required" >&2; exit 2; }; done
gh repo view "$repository" --json isPrivate --jq 'select(.isPrivate == false)' | grep -q false || {
  echo 'Terraform provider repository must exist and be public' >&2
  exit 1
}

mirror="$(mktemp -d)"
gh repo clone "$repository" "$mirror" -- --quiet
find "$mirror" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf -- {} +
git -C "$source_root" archive HEAD | tar -x -C "$mirror"
git -C "$mirror" config user.name "AutoSQL Release"
git -C "$mirror" config user.email "release@autosql.io"
git -C "$mirror" add --all
if ! git -C "$mirror" diff --cached --quiet; then
  git -C "$mirror" commit --quiet -m "Release AutoSQL Terraform provider ${version}"
fi
if git -C "$mirror" rev-parse -q --verify "refs/tags/${version}" >/dev/null; then
  test "$(git -C "$mirror" rev-parse "refs/tags/${version}^{}")" = "$(git -C "$mirror" rev-parse HEAD)" || {
    echo "existing ${version} does not identify the provider source" >&2
    exit 1
  }
else
  git -C "$mirror" tag -a "$version" -m "AutoSQL Terraform provider ${version}"
fi
git -C "$mirror" push --quiet origin HEAD:main "$version"
if gh release view "$version" --repo "$repository" >/dev/null 2>&1; then
  gh release upload "$version" "$assets"/terraform-provider-autosql_* --repo "$repository" --clobber
else
  gh release create "$version" "$assets"/terraform-provider-autosql_* \
    --repo "$repository" --verify-tag --title "AutoSQL Terraform provider ${version}" \
    --notes "Digest-bound AutoSQL schema and migration resources. Provider archives, checksums, signature, and SBOMs are generated by the AutoSQL release gate."
fi
